defaults:
  - dataset: cifar10
  - _self_

hydra:
  searchpath:
    - pkg://additional_conf
    # You can also use file based schema, for example:
    # - file:///etc/my_app
    # - file://${oc.env:HOME}/.my_app
